;; This code was automatically generated by the 'metav' library.
(ns http.meta)

(def module-name "cljs-http")
(def path ".")
(def version "0.1.2")
(def tag "v0.1.2")
(def generated-at "2020-05-13T21:53:31Z")
