;; This code was automatically generated by the 'metav' library.
(ns http.meta)

(def module-name "cljs-http")
(def path ".")
(def version "0.1.1")
(def tag "v0.1.1")
(def generated-at "2020-02-10T05:20:37Z")
